import type { EditorThemeClasses } from "lexical";

export const editorTheme: EditorThemeClasses = {
  paragraph: "mb-2 leading-[1.75] text-[15px]",
  heading: {
    h1: "text-2xl font-bold mb-3 mt-6 leading-tight",
    h2: "text-xl font-semibold mb-2 mt-5 leading-tight",
    h3: "text-[17px] font-semibold mb-2 mt-4 leading-snug",
    h4: "text-base font-semibold mb-1 mt-3",
    h5: "text-sm font-semibold mb-1 mt-3",
    h6: "text-sm font-semibold mb-1 mt-3 text-muted-foreground",
  },
  list: {
    nested: {
      listitem: "ml-6",
    },
    ol: "list-decimal list-outside mb-2 pl-6 leading-[1.6]",
    ul: "list-disc list-outside mb-2 pl-6 leading-[1.6]",
    listitem: "mb-1",
  },
  quote:
    "border-l-[3px] border-accent-primary italic text-secondary pl-4 my-3",
  code: "font-[JetBrains_Mono,monospace] text-[13px] bg-active px-1.5 py-0.5 rounded-[4px]",
  codeHighlight: {
    atrule: "text-purple-400",
    attr: "text-blue-400",
    boolean: "text-orange-400",
    builtin: "text-green-400",
    cdata: "text-gray-400",
    char: "text-green-400",
    "class-name": "text-yellow-400",
    comment: "text-gray-500 italic",
    constant: "text-orange-400",
    deleted: "text-red-400",
    doctype: "text-gray-400",
    entity: "text-orange-400",
    function: "text-blue-400",
    important: "text-yellow-400 italic",
    inserted: "text-green-400",
    keyword: "text-purple-400",
    namespace: "text-yellow-400",
    number: "text-orange-400",
    operator: "text-purple-400",
    prolog: "text-gray-400",
    property: "text-blue-400",
    punctuation: "text-gray-400",
    regex: "text-orange-400",
    selector: "text-green-400",
    string: "text-green-400",
    symbol: "text-orange-400",
    tag: "text-red-400",
    url: "text-blue-400",
    variable: "text-orange-400",
  },
  link: "text-accent-primary underline cursor-pointer hover:text-accent-hover",
  text: {
    bold: "font-semibold",
    italic: "italic",
    strikethrough: "line-through",
    underline: "underline",
    underlineStrikethrough: "underline line-through",
    code: "font-[JetBrains_Mono,monospace] text-[13px] bg-active px-1.5 py-0.5 rounded-[4px]",
  },
};
