/**
 * FileBrowserPerfDemo.tsx
 *
 * File Browser performance improvements for large organisations.
 *
 * ACHIEVEMENTS
 *   - Led major performance improvements for File Browser at scale (10K–100K files)
 *   - Data fetching strategy: cursor pagination, caching, prefetch
 *   - Frontend architecture: virtual scrolling, optimistic updates, normalised state
 *   - Cross-layer redesign: frontend + backend API + database indexes
 *   - Mentored engineers, established scalable FE practices
 *
 * TABS
 *   🐌 The Problem      — what breaks when orgs have 50K files
 *   ⚡ Virtual Scroll    — working demo: 5000 files, only ~12 DOM nodes rendered
 *   🔗 Data Strategy    — cursor pagination, stale-while-revalidate, optimistic updates
 *   👥 Cross-layer      — DB indexes, API redesign, mentoring patterns
 */

import React, { useState, useRef, useCallback, useEffect, useMemo } from "react";

// ─────────────────────────────────────────────────────────────────
// File data — deterministic, generated by index (no Math.random)
// ─────────────────────────────────────────────────────────────────

const FILE_NAMES = ["Report", "Proposal", "Budget", "Design", "Contract", "Invoice", "Notes", "Presentation", "Analysis", "Roadmap", "Spec", "Review"];
const FILE_TYPES = ["pdf", "docx", "xlsx", "png", "jpg", "mp4", "txt", "zip", "pptx", "csv"];
const OWNERS     = ["Alice Chen", "Bob Park", "Carol Smith", "Dave Jones", "Eve Wang", "Frank Lee"];
const DATES      = ["Today", "Yesterday", "2 days ago", "Last week", "2 weeks ago", "Last month"];
const SIZES_KB   = [12, 48, 340, 1200, 4500, 128, 890, 2340, 67, 5600];
const ICON: Record<string, string> = { pdf: "📄", docx: "📝", xlsx: "📊", png: "🖼", jpg: "🖼", mp4: "🎬", txt: "📃", zip: "📦", pptx: "📑", csv: "📊", folder: "📁" };
const TYPE_COLOR: Record<string, string> = { pdf: "#ef4444", docx: "#3b82f6", xlsx: "#22c55e", png: "#ec4899", jpg: "#ec4899", mp4: "#f97316", txt: "#94a3b8", zip: "#a855f7", pptx: "#f59e0b", csv: "#22c55e", folder: "#fbbf24" };

function genFile(i: number) {
  const isFolder = i % 9 === 0;
  const type     = isFolder ? "folder" : FILE_TYPES[i % FILE_TYPES.length];
  const name     = isFolder
    ? `${FILE_NAMES[i % FILE_NAMES.length]} Q${(i % 4) + 1} ${2020 + (i % 5)}`
    : `${FILE_NAMES[i % FILE_NAMES.length]}_v${(i % 4) + 1}.${type}`;
  return {
    id: i,
    name,
    type,
    isFolder,
    size: isFolder ? "—" : `${(SIZES_KB[i % SIZES_KB.length] / 1024).toFixed(1)} MB`,
    owner: OWNERS[i % OWNERS.length],
    modified: DATES[i % DATES.length],
  };
}

// Precompute a page worth of data for the pagination demo
function genPage(page: number, perPage = 20) {
  const start = page * perPage;
  return Array.from({ length: perPage }, (_, j) => genFile(start + j));
}

// ─────────────────────────────────────────────────────────────────
// Virtual list (no react-window dependency)
// ─────────────────────────────────────────────────────────────────

const ROW_HEIGHT     = 40;
const CONTAINER_H    = 400;
const VISIBLE_COUNT  = Math.ceil(CONTAINER_H / ROW_HEIGHT) + 4; // +4 buffer

function FileRow({ file, style }: { file: ReturnType<typeof genFile>; style?: React.CSSProperties }) {
  return (
    <div style={{
      height: ROW_HEIGHT, display: "flex", alignItems: "center", gap: 10, padding: "0 14px",
      borderBottom: "1px solid #1e293b", fontSize: 12, color: "#94a3b8",
      ...style,
    }}>
      <span style={{ fontSize: 15, width: 20, flexShrink: 0 }}>{ICON[file.type]}</span>
      <span style={{ flex: 1, color: "#f1f5f9", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{file.name}</span>
      <span style={{ width: 90, color: TYPE_COLOR[file.type], fontSize: 10, fontWeight: 700 }}>{file.type.toUpperCase()}</span>
      <span style={{ width: 70, textAlign: "right" }}>{file.size}</span>
      <span style={{ width: 100, textAlign: "right" }}>{file.owner.split(" ")[0]}</span>
      <span style={{ width: 100, textAlign: "right" }}>{file.modified}</span>
    </div>
  );
}

function VirtualFileList({ total }: { total: number }) {
  const [scrollTop, setScrollTop]   = useState(0);
  const [renderCount, setRenderCount] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);

  const startIndex   = Math.floor(scrollTop / ROW_HEIGHT);
  const endIndex     = Math.min(startIndex + VISIBLE_COUNT, total);
  const paddingTop   = startIndex * ROW_HEIGHT;
  const paddingBottom = Math.max(0, (total - endIndex) * ROW_HEIGHT);

  // Increment render counter on scroll (demonstrates virtualisation)
  const handleScroll = useCallback((e: React.UIEvent<HTMLDivElement>) => {
    setScrollTop(e.currentTarget.scrollTop);
    setRenderCount(c => c + 1);
  }, []);

  const rows = useMemo(() => {
    const out = [];
    for (let i = startIndex; i < endIndex; i++) {
      out.push(<FileRow key={i} file={genFile(i)} />);
    }
    return out;
  }, [startIndex, endIndex]);

  return (
    <div>
      <div style={{ display: "flex", gap: 16, padding: "8px 14px", background: "#0f172a", borderRadius: "8px 8px 0 0", fontSize: 10, color: "#64748b", fontWeight: 700 }}>
        <span style={{ flex: 1 }}>NAME</span>
        <span style={{ width: 90 }}>TYPE</span>
        <span style={{ width: 70, textAlign: "right" }}>SIZE</span>
        <span style={{ width: 100, textAlign: "right" }}>OWNER</span>
        <span style={{ width: 100, textAlign: "right" }}>MODIFIED</span>
      </div>
      <div
        ref={containerRef}
        onScroll={handleScroll}
        style={{ height: CONTAINER_H, overflowY: "auto", border: "1px solid #334155", borderRadius: "0 0 8px 8px" }}
      >
        <div style={{ paddingTop, paddingBottom }}>
          {rows}
        </div>
      </div>
      <div style={{ display: "flex", gap: 16, marginTop: 8, fontSize: 10, color: "#64748b" }}>
        <span>📂 Total files: <strong style={{ color: "#f1f5f9" }}>{total.toLocaleString()}</strong></span>
        <span>🖼 DOM nodes rendered: <strong style={{ color: "#4ade80" }}>{endIndex - startIndex}</strong></span>
        <span>📍 Scroll position: <strong style={{ color: "#f1f5f9" }}>{Math.round(scrollTop)}px</strong></span>
        <span>↕ First visible row: <strong style={{ color: "#a5b4fc" }}>#{startIndex + 1}</strong></span>
        <span>🔄 Scroll events: <strong style={{ color: "#fbbf24" }}>{renderCount}</strong></span>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────
// Cursor pagination simulation
// ─────────────────────────────────────────────────────────────────

const TOTAL_PAGES = 8;

function usePaginatedFiles() {
  const [pages, setPages]     = useState<ReturnType<typeof genFile>[][]>([]);
  const [cursor, setCursor]   = useState<number>(0);
  const [loading, setLoading] = useState(false);
  const [mode, setMode]       = useState<"offset" | "cursor">("cursor");

  const loadPage = useCallback((pageNum: number) => {
    setLoading(true);
    // Simulate network — "offset" mode is slower because DB scans more rows
    const delay = mode === "offset" ? 900 + pageNum * 180 : 280;
    setTimeout(() => {
      setPages(prev => [...prev, genPage(pageNum)]);
      setCursor(pageNum + 1);
      setLoading(false);
    }, delay);
  }, [mode]);

  const reset = useCallback(() => { setPages([]); setCursor(0); }, []);

  useEffect(() => {
    setPages([]);
    setCursor(0);
  }, [mode]);

  return { pages, cursor, loading, loadPage, reset, hasMore: cursor < TOTAL_PAGES, mode, setMode };
}

// ─────────────────────────────────────────────────────────────────
// Code block
// ─────────────────────────────────────────────────────────────────

function CodeBlock({ code, label, color = "#64748b" }: { code: string; label?: string; color?: string }) {
  return (
    <div style={{ background: "#0f172a", borderRadius: 8, overflow: "hidden" }}>
      {label && <div style={{ padding: "6px 12px", borderBottom: "1px solid #1e293b", fontSize: 10, color }}>{label}</div>}
      <pre style={{ margin: 0, padding: 14, fontSize: 10, fontFamily: "monospace", color: "#94a3b8", lineHeight: 1.7, overflow: "auto", maxHeight: 340 }}>{code}</pre>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────

export function FileBrowserPerfDemo() {
  const [activeTab, setActiveTab] = useState<"problem" | "virtual" | "data" | "cross">("problem");
  const [virtualTotal, setVirtualTotal] = useState(5000);
  const { pages, cursor, loading, loadPage, reset, hasMore, mode, setMode } = usePaginatedFiles();

  const allFiles = useMemo(() => pages.flat(), [pages]);

  const TABS = [
    { id: "problem" as const, label: "🐌 The Problem" },
    { id: "virtual" as const, label: "⚡ Virtual Scroll" },
    { id: "data"    as const, label: "🔗 Data Strategy" },
    { id: "cross"   as const, label: "👥 Cross-layer" },
  ];

  return (
    <div style={{ background: "#0f172a", color: "#f1f5f9", fontFamily: "'Inter', system-ui, sans-serif", minHeight: "100vh", padding: 24 }}>

      {/* Header */}
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
          <span style={{ fontSize: 28 }}>📂</span>
          <div>
            <h1 style={{ margin: 0, fontSize: 22, fontWeight: 800 }}>File Browser — Performance at Scale</h1>
            <p style={{ margin: 0, color: "#64748b", fontSize: 13 }}>
              Virtual scrolling · Cursor pagination · Cross-layer optimisation · Mentoring
            </p>
          </div>
        </div>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          {["Performance Engineering", "Virtual DOM", "Cursor Pagination", "Caching", "Optimistic Updates", "DB Indexing", "Cross-layer Architecture", "Mentoring"].map(t => (
            <span key={t} style={{ background: "#1e293b", color: "#94a3b8", border: "1px solid #334155", borderRadius: 20, padding: "3px 10px", fontSize: 11 }}>{t}</span>
          ))}
        </div>
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", gap: 4, marginBottom: 20, borderBottom: "1px solid #1e293b", paddingBottom: 4, flexWrap: "wrap" }}>
        {TABS.map(tab => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)} style={{
            background: activeTab === tab.id ? "#1e293b" : "transparent",
            color: activeTab === tab.id ? "#f1f5f9" : "#64748b",
            border: activeTab === tab.id ? "1px solid #334155" : "1px solid transparent",
            borderRadius: "8px 8px 0 0", padding: "8px 18px", cursor: "pointer", fontSize: 13, fontWeight: 600,
          }}>{tab.label}</button>
        ))}
      </div>

      {/* ── THE PROBLEM ── */}
      {activeTab === "problem" && (
        <div>
          <div style={{ background: "#1e293b", border: "1px solid #ef444430", borderRadius: 10, padding: 16, marginBottom: 20 }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: "#fca5a5", marginBottom: 8 }}>What "large organisation" actually means for a File Browser</div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, marginBottom: 12 }}>
              {[
                { label: "Files in root folder", small: "~50", large: "50,000–200,000" },
                { label: "Folder depth",          small: "3–4 levels", large: "10–15 levels" },
                { label: "Concurrent users",      small: "1–5", large: "500–5000" },
                { label: "Permissions to check",  small: "org-wide", large: "per-file, per-user" },
                { label: "Sort/filter scope",     small: "client-side", large: "must be server-side" },
                { label: "Real-time updates",     small: "not needed", large: "critical (collaboration)" },
              ].map(row => (
                <div key={row.label} style={{ background: "#0f172a", borderRadius: 8, padding: 10 }}>
                  <div style={{ fontSize: 10, color: "#64748b", marginBottom: 6 }}>{row.label}</div>
                  <div style={{ display: "flex", gap: 8 }}>
                    <div style={{ fontSize: 10, color: "#94a3b8" }}>Small org: <strong style={{ color: "#f1f5f9" }}>{row.small}</strong></div>
                    <div style={{ fontSize: 10, color: "#94a3b8" }}>Large org: <strong style={{ color: "#f59e0b" }}>{row.large}</strong></div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: "#ef4444", marginBottom: 8 }}>❌ BEFORE — Naive implementation</div>
              <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                {[
                  { metric: "Page load for 10K-file folder", value: "12–18 seconds", icon: "⏱" },
                  { metric: "DOM nodes rendered",            value: "10,000+ (browser freezes)", icon: "🖥" },
                  { metric: "API response",                  value: "Single req: all files at once", icon: "📡" },
                  { metric: "API response size",             value: "12MB+ JSON payload", icon: "📦" },
                  { metric: "Scroll performance",            value: "5 fps (janky)", icon: "📉" },
                  { metric: "Sort by date on 50K files",     value: "Crashes browser tab", icon: "💥" },
                  { metric: "Permission check",              value: "Post-fetch filter (slow)", icon: "🔒" },
                ].map(r => (
                  <div key={r.metric} style={{ background: "#1e293b", borderRadius: 8, padding: "8px 12px", display: "flex", gap: 8, borderLeft: "3px solid #ef4444" }}>
                    <span style={{ fontSize: 14 }}>{r.icon}</span>
                    <div>
                      <div style={{ fontSize: 10, color: "#64748b" }}>{r.metric}</div>
                      <div style={{ fontSize: 11, fontWeight: 700, color: "#ef4444" }}>{r.value}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: "#4ade80", marginBottom: 8 }}>✅ AFTER — Performance redesign</div>
              <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                {[
                  { metric: "Page load for 10K-file folder", value: "< 400ms (first 20 files)", icon: "⚡" },
                  { metric: "DOM nodes rendered",            value: "~12 (virtual scroll)", icon: "🖥" },
                  { metric: "API response",                  value: "Cursor pagination: 20 at a time", icon: "📡" },
                  { metric: "API response size",             value: "~48KB per page", icon: "📦" },
                  { metric: "Scroll performance",            value: "60 fps (butter smooth)", icon: "📈" },
                  { metric: "Sort by date on 50K files",     value: "Server-side: 80ms", icon: "✅" },
                  { metric: "Permission check",              value: "At query time (DB filtered)", icon: "🔒" },
                ].map(r => (
                  <div key={r.metric} style={{ background: "#1e293b", borderRadius: 8, padding: "8px 12px", display: "flex", gap: 8, borderLeft: "3px solid #4ade80" }}>
                    <span style={{ fontSize: 14 }}>{r.icon}</span>
                    <div>
                      <div style={{ fontSize: 10, color: "#64748b" }}>{r.metric}</div>
                      <div style={{ fontSize: 11, fontWeight: 700, color: "#4ade80" }}>{r.value}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── VIRTUAL SCROLL ── */}
      {activeTab === "virtual" && (
        <div>
          <div style={{ background: "#1e293b", border: "1px solid #4ade8030", borderRadius: 10, padding: 14, marginBottom: 16 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: "#86efac", marginBottom: 4 }}>Virtual scrolling — the solution to DOM explosion</div>
            <div style={{ fontSize: 12, color: "#94a3b8", lineHeight: 1.7 }}>
              Rendering 10,000 DOM rows means <strong style={{ color: "#f1f5f9" }}>10,000 layout boxes, 10,000 event listeners</strong>,
              60,000+ style calculations on every paint. The browser freezes.
              Virtual scrolling renders <strong style={{ color: "#4ade80" }}>only the rows visible on screen</strong> (~12) plus a small buffer.
              As you scroll, rows are created and destroyed. Total DOM nodes: constant, regardless of file count.
            </div>
          </div>

          {/* File count selector */}
          <div style={{ display: "flex", gap: 8, marginBottom: 14, alignItems: "center" }}>
            <span style={{ fontSize: 11, color: "#64748b" }}>Total files:</span>
            {[100, 1000, 5000, 50000].map(n => (
              <button key={n} onClick={() => setVirtualTotal(n)} style={{
                background: virtualTotal === n ? "#6366f120" : "#1e293b",
                border: `1px solid ${virtualTotal === n ? "#6366f1" : "#334155"}`,
                borderRadius: 6, padding: "5px 12px", cursor: "pointer",
                color: virtualTotal === n ? "#a5b4fc" : "#64748b", fontSize: 11,
              }}>{n.toLocaleString()}</button>
            ))}
            <span style={{ fontSize: 10, color: "#334155", marginLeft: 8 }}>
              Naive: {virtualTotal.toLocaleString()} DOM nodes → {virtualTotal > 5000 ? "browser crash" : virtualTotal > 1000 ? "severe lag" : "sluggish"}
            </span>
          </div>

          <VirtualFileList total={virtualTotal} />

          <div style={{ marginTop: 14 }}>
            <CodeBlock label="Virtual scroll implementation — no library required" color="#4ade80" code={
`const ROW_HEIGHT    = 40;    // px — every row is the same height
const CONTAINER_H   = 400;   // px — visible window
const BUFFER        = 4;     // extra rows above and below viewport

function VirtualFileList({ total }: { total: number }) {
  const [scrollTop, setScrollTop] = useState(0);

  // Calculate which rows are visible
  const startIndex    = Math.floor(scrollTop / ROW_HEIGHT);
  const visibleCount  = Math.ceil(CONTAINER_H / ROW_HEIGHT) + BUFFER;
  const endIndex      = Math.min(startIndex + visibleCount, total);

  // Spacers create correct scrollbar height without rendering all rows
  const paddingTop    = startIndex * ROW_HEIGHT;
  const paddingBottom = Math.max(0, (total - endIndex) * ROW_HEIGHT);

  return (
    <div
      style={{ height: CONTAINER_H, overflowY: "auto" }}
      onScroll={e => setScrollTop(e.currentTarget.scrollTop)}
    >
      {/* Total height = total * rowHeight, but only 12 rows rendered */}
      <div style={{ paddingTop, paddingBottom }}>
        {Array.from({ length: endIndex - startIndex }, (_, i) =>
          <FileRow key={startIndex + i} file={genFile(startIndex + i)} />
        )}
      </div>
    </div>
  );
}

// KEY INSIGHT: DOM nodes = ~12, always.
// Scrollbar reflects full 50,000-file height via paddingBottom.
// Scroll is 60fps because only 12 rows participate in layout.`} />
          </div>
        </div>
      )}

      {/* ── DATA STRATEGY ── */}
      {activeTab === "data" && (
        <div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 14 }}>
            <div>
              <div style={{ display: "flex", gap: 6, marginBottom: 12 }}>
                {(["cursor", "offset"] as const).map(m => (
                  <button key={m} onClick={() => { setMode(m); reset(); }} style={{
                    background: mode === m ? "#6366f120" : "#1e293b",
                    border: `1px solid ${mode === m ? "#6366f1" : "#334155"}`,
                    borderRadius: 8, padding: "7px 14px", cursor: "pointer",
                    color: mode === m ? "#a5b4fc" : "#64748b", fontSize: 12,
                  }}>
                    {m === "cursor" ? "✅ Cursor pagination" : "❌ Offset pagination"}
                  </button>
                ))}
              </div>

              {/* Explanation panel */}
              <div style={{ background: "#1e293b", border: `1px solid ${mode === "cursor" ? "#4ade8030" : "#ef444430"}`, borderRadius: 10, padding: 12, marginBottom: 12 }}>
                {mode === "cursor" ? (
                  <>
                    <div style={{ fontSize: 11, fontWeight: 700, color: "#4ade80", marginBottom: 6 }}>Cursor pagination — scales to any depth</div>
                    <div style={{ fontSize: 11, color: "#94a3b8", lineHeight: 1.7 }}>
                      Each response includes a <code style={{ background: "#0f172a", padding: "1px 4px", borderRadius: 3 }}>cursor</code> pointing to the last returned item.
                      The next page query starts from that cursor — the database uses an index to locate it instantly.
                      Speed is constant regardless of page depth.
                    </div>
                    <div style={{ marginTop: 8, fontSize: 9, fontFamily: "monospace", color: "#4ade80", background: "#0f172a", padding: 8, borderRadius: 4 }}>
                      SELECT * FROM files WHERE id &gt; :cursor ORDER BY id LIMIT 20
                    </div>
                  </>
                ) : (
                  <>
                    <div style={{ fontSize: 11, fontWeight: 700, color: "#ef4444", marginBottom: 6 }}>Offset pagination — breaks at scale</div>
                    <div style={{ fontSize: 11, color: "#94a3b8", lineHeight: 1.7 }}>
                      <code style={{ background: "#0f172a", padding: "1px 4px", borderRadius: 3 }}>OFFSET 10000</code> means the database scans and discards 10,000 rows before returning 20.
                      Page 1 is fast. Page 500 is 250× slower.
                    </div>
                    <div style={{ marginTop: 8, fontSize: 9, fontFamily: "monospace", color: "#ef4444", background: "#0f172a", padding: 8, borderRadius: 4 }}>
                      SELECT * FROM files ORDER BY id LIMIT 20 OFFSET {cursor * 20}
                      {"\n"}-- Scans {cursor * 20} rows just to skip them
                    </div>
                  </>
                )}
              </div>

              {/* Loaded pages */}
              <div style={{ background: "#1e293b", border: "1px solid #334155", borderRadius: 10, overflow: "hidden", marginBottom: 10 }}>
                <div style={{ padding: "8px 12px", background: "#0f172a", fontSize: 10, color: "#64748b", borderBottom: "1px solid #334155" }}>
                  Files loaded: {allFiles.length} · Pages: {pages.length}/{TOTAL_PAGES}
                  {mode === "offset" && cursor > 2 && <span style={{ color: "#ef4444", marginLeft: 8 }}>⚠ Getting slower…</span>}
                </div>
                <div style={{ maxHeight: 300, overflowY: "auto" }}>
                  {allFiles.slice(0, 40).map(file => (
                    <div key={file.id} style={{ padding: "6px 12px", borderBottom: "1px solid #1e293b", display: "flex", gap: 10, fontSize: 11 }}>
                      <span>{ICON[file.type]}</span>
                      <span style={{ flex: 1, color: "#f1f5f9" }}>{file.name}</span>
                      <span style={{ color: "#64748b" }}>{file.modified}</span>
                    </div>
                  ))}
                  {allFiles.length > 40 && (
                    <div style={{ padding: "6px 12px", fontSize: 10, color: "#64748b" }}>… and {allFiles.length - 40} more</div>
                  )}
                </div>
              </div>

              <div style={{ display: "flex", gap: 6 }}>
                <button
                  onClick={() => loadPage(cursor)}
                  disabled={loading || !hasMore}
                  style={{ background: "#4f46e5", border: "none", borderRadius: 8, padding: "8px 16px", color: "#fff", cursor: "pointer", fontSize: 12, opacity: (loading || !hasMore) ? 0.5 : 1 }}
                >
                  {loading ? "Loading…" : hasMore ? `Load next 20 (page ${cursor + 1})` : "All loaded"}
                </button>
                <button onClick={reset} style={{ background: "#1e293b", border: "1px solid #334155", borderRadius: 8, padding: "8px 12px", color: "#64748b", cursor: "pointer", fontSize: 11 }}>Reset</button>
              </div>
              {mode === "offset" && <div style={{ marginTop: 6, fontSize: 10, color: "#ef4444" }}>Notice: each page loads slower as you go deeper (simulated DB scan overhead)</div>}
            </div>

            <div>
              <CodeBlock label="Cursor pagination — API contract" color="#4ade80" code={
`// GET /api/folders/:folderId/files
// ?cursor=eyJpZCI6MTAwMH0&limit=20&sort=modified_desc

// Response:
{
  "items": [
    { "id": "f_1001", "name": "Q3 Budget.xlsx", "type": "xlsx",
      "size": 340000, "modified": "2024-08-12T14:23:01Z",
      "permissions": { "canView": true, "canEdit": false } },
    // ... 19 more
  ],
  "cursor": "eyJpZCI6MTAyMH0",  // opaque: base64({"id":1020})
  "hasMore": true,
  "total": 48392               // for progress indicator only
}

// NEXT PAGE:
// GET /api/folders/:folderId/files
// ?cursor=eyJpZCI6MTAyMH0&limit=20

// DB query (fast — uses index):
// SELECT * FROM files
// WHERE folder_id = :folderId
//   AND id > :cursor_id        ← index seek
//   AND visible_to(:userId)    ← permission check at query time
// ORDER BY id LIMIT 20`} />

              <div style={{ marginTop: 10 }}>
                <CodeBlock label="Stale-while-revalidate + optimistic updates" color="#f59e0b" code={
`// Cache strategy: show stale data immediately, refresh in background
// SWR pattern — used for every page of file listings

const cache = new Map<string, FileListResponse>();

async function getFiles(folderId: string, cursor?: string) {
  const cacheKey = \`\${folderId}:\${cursor ?? "start"}\`;

  // 1. Return cached data immediately (stale) — zero perceived latency
  if (cache.has(cacheKey)) {
    notifySubscribers(cacheKey, cache.get(cacheKey)!);
  }

  // 2. Revalidate in background — update if data changed
  const fresh = await api.getFiles(folderId, cursor);
  if (!isEqual(fresh, cache.get(cacheKey))) {
    cache.set(cacheKey, fresh);
    notifySubscribers(cacheKey, fresh);
  }
}

// Optimistic update — delete feels instant
async function deleteFile(fileId: string, folderId: string) {
  // 1. Update UI immediately (remove from list)
  optimisticRemove(fileId);

  try {
    // 2. Confirm with server
    await api.deleteFile(fileId);
    // Success — optimistic update stays
  } catch (err) {
    // 3. Rollback on failure
    optimisticRestore(fileId);
    showError("Could not delete file. Please try again.");
  }
}`} />
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── CROSS-LAYER ── */}
      {activeTab === "cross" && (
        <div>
          <div style={{ background: "#1e293b", border: "1px solid #6366f130", borderRadius: 10, padding: 14, marginBottom: 16 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: "#a5b4fc", marginBottom: 6 }}>Why FE performance requires cross-layer thinking</div>
            <div style={{ fontSize: 12, color: "#94a3b8", lineHeight: 1.7 }}>
              Virtual scrolling fixes DOM performance. But if the API still returns <strong style={{ color: "#f1f5f9" }}>12MB of JSON</strong> in a single response,
              the first contentful paint is still 18 seconds. If the database uses <strong style={{ color: "#f1f5f9" }}>offset pagination</strong> internally,
              page 500 is 250× slower than page 1 regardless of what the frontend does.
              Real performance requires frontend, backend, and database changes to work together.
            </div>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, marginBottom: 14 }}>
            {[
              {
                layer: "Database", icon: "🗄", color: "#ef4444",
                problems: ["Full table scan for sort (no index)", "Permission check post-fetch (slow)", "No count cache — COUNT(*) on 100K rows", "Offset pagination gets slower over time"],
                fixes: ["Composite index: (folder_id, modified_at)", "Filter by permission AT QUERY TIME", "Cached file counts (updated on write)", "Cursor: id > :last_seen_id (index seek)"],
              },
              {
                layer: "Backend API", icon: "⚙", color: "#f59e0b",
                problems: ["One endpoint, all files, no pagination", "Sort/filter done in-memory after fetch", "File metadata: all fields in one response", "No cache headers on listing endpoints"],
                fixes: ["Cursor pagination (20/page)", "Server-side sort (query ORDER BY)", "Field selection: ?fields=id,name,type,size", "ETags + Cache-Control for list endpoints"],
              },
              {
                layer: "Frontend", icon: "🖥", color: "#4ade80",
                problems: ["Render all 10K rows as DOM nodes", "Re-fetch folder on every navigation", "File operations block UI (await then reload)", "Sort triggers full re-render of all rows"],
                fixes: ["Virtual scrolling (12 DOM nodes always)", "SWR cache: show stale, revalidate in BG", "Optimistic updates for rename/delete/move", "Stable row keys + React.memo (no re-render)"],
              },
            ].map(col => (
              <div key={col.layer} style={{ background: "#1e293b", borderRadius: 10, overflow: "hidden" }}>
                <div style={{ padding: "10px 14px", background: "#0f172a", borderBottom: "1px solid #334155" }}>
                  <span style={{ fontSize: 16, marginRight: 8 }}>{col.icon}</span>
                  <span style={{ fontSize: 12, fontWeight: 700, color: col.color }}>{col.layer}</span>
                </div>
                <div style={{ padding: 12 }}>
                  <div style={{ fontSize: 10, fontWeight: 700, color: "#ef4444", marginBottom: 6 }}>Problems</div>
                  {col.problems.map(p => <div key={p} style={{ fontSize: 10, color: "#64748b", marginBottom: 3, display: "flex", gap: 4 }}><span style={{ color: "#ef4444" }}>✗</span>{p}</div>)}
                  <div style={{ fontSize: 10, fontWeight: 700, color: "#4ade80", margin: "10px 0 6px" }}>Fixes</div>
                  {col.fixes.map(f => <div key={f} style={{ fontSize: 10, color: "#94a3b8", marginBottom: 3, display: "flex", gap: 4 }}><span style={{ color: "#4ade80" }}>✓</span>{f}</div>)}
                </div>
              </div>
            ))}
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
            <div style={{ background: "#1e293b", border: "1px solid #334155", borderRadius: 10, padding: 14 }}>
              <div style={{ fontSize: 11, fontWeight: 700, marginBottom: 10 }}>👥 Mentoring patterns introduced</div>
              {[
                { title: "Performance RFC process", detail: "Before writing code: write a one-page doc — problem, metric, proposed solution, expected result. Review as a team. Prevents building the wrong thing." },
                { title: "\"Measure before fix\" rule", detail: "All performance work starts with a measurement. No guessing. Use Chrome DevTools Performance tab, React Profiler, and real user metrics (Web Vitals)." },
                { title: "Paired code review for complexity", detail: "Virtual scroll, cursor pagination, optimistic updates — complex code gets paired review. Reviewer must run the code, not just read it." },
                { title: "\"What would break this at scale?\" check", detail: "For every PR touching data fetching: team asks this question explicitly. Forces engineers to think about 10K vs 10 files early." },
              ].map(item => (
                <div key={item.title} style={{ borderLeft: "3px solid #6366f1", paddingLeft: 10, marginBottom: 12 }}>
                  <div style={{ fontSize: 11, fontWeight: 700, color: "#a5b4fc", marginBottom: 3 }}>{item.title}</div>
                  <div style={{ fontSize: 11, color: "#64748b" }}>{item.detail}</div>
                </div>
              ))}
            </div>

            <div>
              <CodeBlock label="DB index that enabled cursor pagination and sort" color="#ef4444" code={
`-- BEFORE: full table scan for every listing query
EXPLAIN SELECT * FROM files
WHERE folder_id = 'abc123'
ORDER BY modified_at DESC
LIMIT 20;
-- → Seq Scan on files (cost=0..8920.00 rows=100000)
-- → Sort on modified_at (slow, no index)

-- ADDED: composite index covering folder + sort + cursor
CREATE INDEX idx_files_folder_modified
ON files (folder_id, modified_at DESC, id)
WHERE deleted_at IS NULL;

-- AFTER: index-only scan
EXPLAIN SELECT id, name, type, size, modified_at
FROM files
WHERE folder_id = 'abc123'
  AND (modified_at, id) < (:last_modified, :last_id)  ← cursor
ORDER BY modified_at DESC, id DESC
LIMIT 20;
-- → Index Scan using idx_files_folder_modified
-- → cost=0..0.68 rows=20  (250× improvement at page 500)

-- Permission filter — done at query time, not post-fetch
-- JOIN file_permissions fp
-- ON fp.file_id = files.id
-- AND fp.user_id = :userId
-- AND fp.can_view = true`} />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default FileBrowserPerfDemo;
